In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/telecom_churn.csv')

In [ ]:
data.head(15)

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,1,Reliance Jio,F,25,Karnataka,Kolkata,755597,2020-01-01,4,124962,44,45,-361,0
1,2,Reliance Jio,F,55,Mizoram,Mumbai,125926,2020-01-01,2,130556,62,39,5973,0
2,3,Vodafone,F,57,Arunachal Pradesh,Delhi,423976,2020-01-01,0,148828,49,24,193,1
3,4,BSNL,M,46,Tamil Nadu,Kolkata,522841,2020-01-01,1,38722,80,25,9377,1
4,5,BSNL,F,26,Tripura,Delhi,740247,2020-01-01,2,55098,78,15,1393,0
5,6,Vodafone,M,36,Uttarakhand,Chennai,120612,2020-01-01,1,73452,91,24,8109,0
6,7,BSNL,F,60,Karnataka,Delhi,609616,2020-01-01,1,110035,36,13,8512,0
7,8,BSNL,M,46,Arunachal Pradesh,Kolkata,866786,2020-01-01,4,104541,87,40,2245,1
8,9,Reliance Jio,F,53,Himachal Pradesh,Mumbai,765257,2020-01-01,2,79439,34,12,10039,0
9,10,BSNL,F,57,Rajasthan,Mumbai,506308,2020-01-01,0,126422,61,33,567,0
10,11,Airtel,M,44,Uttarakhand,Chennai,776250,2020-01-01,0,133288,7,7,1275,1
11,12,Airtel,M,56,Odisha,Mumbai,642121,2020-01-01,4,135129,39,51,7644,0
12,13,Vodafone,F,64,Uttar Pradesh,Hyderabad,339770,2020-01-01,4,136967,40,4,1911,0
13,14,Vodafone,F,70,Chhattisgarh,Kolkata,711206,2020-01-01,0,140219,50,17,7727,0
14,15,Vodafone,F,38,Uttar Pradesh,Delhi,546253,2020-01-01,1,147805,86,20,8058,0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243553 entries, 0 to 243552
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           243553 non-null  int64
 1   telecom_partner       243553 non-null  object
 2   gender                243553 non-null  object
 3   age                   243553 non-null  int64
 4   state                 243553 non-null  object
 5   city                  243553 non-null  object
 6   pincode               243553 non-null  int64
 7   date_of_registration  243553 non-null  object
 8   num_dependents        243553 non-null  int64
 9   estimated_salary      243553 non-null  int64
 10  calls_made            243553 non-null  int64
 11  sms_sent              243553 non-null  int64
 12  data_used             243553 non-null  int64
 13  churn                 243553 non-null  int64
dtypes: int64(9), object(5)
memory usage: 26.0+ MB

customer_id

customer_id is the same as the entry position + 1. customer_id will not be used in analysis and building machine learning model. So, customer_id will be dropped.

In [ ]:
# Drop customer_id column
data.drop('customer_id', axis=1, inplace=True)

<ipython-input-146-f70434b885d8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('customer_id', axis=1, inplace=True)

pincode

According to "Handling The Formula of Attribute Data" section, pincode data have many contradictions with city and state columns. So, pincode column will be dropped.

In [ ]:
# Drop pincode column
data.drop('pincode', axis=1, inplace=True)

<ipython-input-147-d27b51686112>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('pincode', axis=1, inplace=True)

date of registration column

According to the original formula of date_of_registration, date_of_registration column will be dropped.

In [ ]:
# Drop date_of_registration column
data.drop('date_of_registration', axis=1, inplace=True)

<ipython-input-148-d5e8da3a153b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop('date_of_registration', axis=1, inplace=True)

churn column

churn column is the objective of the whole project. So churn column wil not be dropped.